// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	GetOrderByOrderUuidOperation OperationName = "GetOrderByOrderUuid"
	PostOrderOperation           OperationName = "PostOrder"
	PostOrderCancelOperation     OperationName = "PostOrderCancel"
	PostOrderPayOperation        OperationName = "PostOrderPay"
)
