// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetOrderByOrderUuid implements GetOrderByOrderUuid operation.
//
// Получить информацию о заказе.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByOrderUuid(ctx context.Context, params GetOrderByOrderUuidParams) (r GetOrderByOrderUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOrder implements PostOrder operation.
//
// Создать заказ.
//
// POST /api/v1/orders
func (UnimplementedHandler) PostOrder(ctx context.Context, req *CreateOrderRequest) (r PostOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOrderCancel implements PostOrderCancel operation.
//
// Отменить заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) PostOrderCancel(ctx context.Context, params PostOrderCancelParams) (r PostOrderCancelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostOrderPay implements PostOrderPay operation.
//
// Оплатить заказ.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PostOrderPay(ctx context.Context, req *PayOrderRequest, params PostOrderPayParams) (r PostOrderPayRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
