// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetOrderByOrderUuidParams is parameters of GetOrderByOrderUuid operation.
type GetOrderByOrderUuidParams struct {
	// Uuid заказа.
	OrderUUID uuid.UUID
}

func unpackGetOrderByOrderUuidParams(packed middleware.Parameters) (params GetOrderByOrderUuidParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetOrderByOrderUuidParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOrderByOrderUuidParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// PostOrderCancelParams is parameters of PostOrderCancel operation.
type PostOrderCancelParams struct {
	// Uuid заказа.
	OrderUUID uuid.UUID
}

func unpackPostOrderCancelParams(packed middleware.Parameters) (params PostOrderCancelParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodePostOrderCancelParams(args [1]string, argsEscaped bool, r *http.Request) (params PostOrderCancelParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// PostOrderPayParams is parameters of PostOrderPay operation.
type PostOrderPayParams struct {
	// Uuid заказа.
	OrderUUID uuid.UUID
}

func unpackPostOrderPayParams(packed middleware.Parameters) (params PostOrderPayParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodePostOrderPayParams(args [1]string, argsEscaped bool, r *http.Request) (params PostOrderPayParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
