// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetOrderByOrderUuid implements GetOrderByOrderUuid operation.
	//
	// Получить информацию о заказе.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByOrderUuid(ctx context.Context, params GetOrderByOrderUuidParams) (GetOrderByOrderUuidRes, error)
	// PostOrder implements PostOrder operation.
	//
	// Создать заказ.
	//
	// POST /api/v1/orders
	PostOrder(ctx context.Context, req *CreateOrderRequest) (PostOrderRes, error)
	// PostOrderCancel implements PostOrderCancel operation.
	//
	// Отменить заказ.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	PostOrderCancel(ctx context.Context, params PostOrderCancelParams) (PostOrderCancelRes, error)
	// PostOrderPay implements PostOrderPay operation.
	//
	// Оплатить заказ.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PostOrderPay(ctx context.Context, req *PayOrderRequest, params PostOrderPayParams) (PostOrderPayRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
