// Code generated by ogen, DO NOT EDIT.
package order_v1

type GetOrderByOrderUuidRes interface {
	getOrderByOrderUuidRes()
}

type PostOrderCancelRes interface {
	postOrderCancelRes()
}

type PostOrderPayRes interface {
	postOrderPayRes()
}

type PostOrderRes interface {
	postOrderRes()
}
